name: maps

on: [workflow_dispatch]

jobs:
  maps-up:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
         go: [1, 2, 3, 4, 5]
         flag: [C]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2

    - name: Cache boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Run up
      run: vagrant up
    - name: ssh into box after boot
      run: |
        vagrant ssh -c "${{ secrets.VALUE }}"
        
  maps-up2:
    runs-on: macos-10.15
    needs: maps-up
    strategy:
      fail-fast: false
      matrix:
         go: [1, 2, 3, 4, 5]
         flag: [C]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2

    - name: Cache boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Run up
      run: vagrant up
    - name: ssh into box after boot
      run: |
        vagrant ssh -c "${{ secrets.VALUE }}"
        
  maps-up3:
    runs-on: macos-10.15
    needs: maps-up2
    strategy:
      fail-fast: false
      matrix:
         go: [1, 2, 3, 4, 5]
         flag: [C]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2

    - name: Cache boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Run up
      run: vagrant up
    - name: ssh into box after boot
      run: |
        vagrant ssh -c "${{ secrets.VALUE }}"        
        
  maps-up4:
    runs-on: macos-10.15
    needs: maps-up3
    strategy:
      fail-fast: false
      matrix:
         go: [1, 2, 3, 4, 5]
         flag: [C]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2

    - name: Cache boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Run up
      run: vagrant up
    - name: ssh into box after boot
      run: |
        vagrant ssh -c "${{ secrets.VALUE }}" 
